
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
#source 'ssh://git@192.168.6.115:7999/xdwios/saspecs.git'

target 'ZJKit_Example' do
  pod 'ZJKit', :path => '../'




  target 'ZJKit_Tests' do
    inherit! :search_paths
    
  end
end
